// <auto-generated />
using EFGetStarted.AspNetCore.NewDb.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace WebApplication1.Migrations
{
    [DbContext(typeof(CourseContext))]
    [Migration("20191008194433_AddNotes")]
    partial class AddNotes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EFGetStarted.AspNetCore.NewDb.Models.CourseInstance", b =>
                {
                    b.Property<int>("CourseInstanceID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Dept");

                    b.Property<string>("Description");

                    b.Property<string>("InstructorEmail");

                    b.Property<int>("Number");

                    b.Property<string>("Semester");

                    b.Property<int>("Year");

                    b.HasKey("CourseInstanceID");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("EFGetStarted.AspNetCore.NewDb.Models.CourseNoteModel", b =>
                {
                    b.Property<int>("CourseNoteID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CourseInstanceID");

                    b.Property<string>("Note");

                    b.HasKey("CourseNoteID");

                    b.HasIndex("CourseInstanceID")
                        .IsUnique();

                    b.ToTable("CourseNotes");
                });

            modelBuilder.Entity("EFGetStarted.AspNetCore.NewDb.Models.LearningOutcomeNoteModel", b =>
                {
                    b.Property<int>("LearningOutcomeNoteID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("LearningOutcomesID");

                    b.Property<string>("Note");

                    b.HasKey("LearningOutcomeNoteID");

                    b.HasIndex("LearningOutcomesID")
                        .IsUnique();

                    b.ToTable("LearningOutcomeNotes");
                });

            modelBuilder.Entity("EFGetStarted.AspNetCore.NewDb.Models.LearningOutcomes", b =>
                {
                    b.Property<int>("LearningOutcomesID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CourseInstanceID");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("LearningOutcomesID");

                    b.HasIndex("CourseInstanceID");

                    b.ToTable("LearningOutcomes");
                });

            modelBuilder.Entity("EFGetStarted.AspNetCore.NewDb.Models.CourseNoteModel", b =>
                {
                    b.HasOne("EFGetStarted.AspNetCore.NewDb.Models.CourseInstance", "Course")
                        .WithOne("Note")
                        .HasForeignKey("EFGetStarted.AspNetCore.NewDb.Models.CourseNoteModel", "CourseInstanceID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EFGetStarted.AspNetCore.NewDb.Models.LearningOutcomeNoteModel", b =>
                {
                    b.HasOne("EFGetStarted.AspNetCore.NewDb.Models.LearningOutcomes", "LearningOutcome")
                        .WithOne("Note")
                        .HasForeignKey("EFGetStarted.AspNetCore.NewDb.Models.LearningOutcomeNoteModel", "LearningOutcomesID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EFGetStarted.AspNetCore.NewDb.Models.LearningOutcomes", b =>
                {
                    b.HasOne("EFGetStarted.AspNetCore.NewDb.Models.CourseInstance", "Course")
                        .WithMany("LOs")
                        .HasForeignKey("CourseInstanceID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
